Something releated to promise:
    try-catch
    return
    then-catch
Conclusion:
    In promise:
        throw = reject
        return = not res, rej
        return another promise not efect